[package]
name = "benches"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

fliplru = { path = ".." }
hashlru = "0.11.0"
lru = "0.9"
caches = "0.2"

